// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cardsearch.sql

package database

import (
	"context"
	"database/sql"
)

const countCardsByNameList = `-- name: CountCardsByNameList :one
SELECT COUNT(*)  FROM cards
WHERE printed_name ILIKE '%' || $1 || '%' AND lang = $2 AND 'paper' = ANY(games)
`

type CountCardsByNameListParams struct {
	Column1 sql.NullString
	Lang    string
}

func (q *Queries) CountCardsByNameList(ctx context.Context, arg CountCardsByNameListParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCardsByNameList, arg.Column1, arg.Lang)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCardsByNameListEng = `-- name: CountCardsByNameListEng :one
SELECT COUNT(*) FROM cards
WHERE name ILIKE '%' || $1 || '%' AND lang = 'en' AND 'paper' = ANY(games)
`

func (q *Queries) CountCardsByNameListEng(ctx context.Context, dollar_1 sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCardsByNameListEng, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const doesLangExist = `-- name: DoesLangExist :one
SELECT name FROM cards WHERE lang = $1 LIMIT 1
`

func (q *Queries) DoesLangExist(ctx context.Context, lang string) (string, error) {
	row := q.db.QueryRowContext(ctx, doesLangExist, lang)
	var name string
	err := row.Scan(&name)
	return name, err
}

const searchCardsByNameList = `-- name: SearchCardsByNameList :many
SELECT printed_name, set_name, set_code, rarity FROM cards
WHERE printed_name ILIKE '%' || $1 || '%' AND lang = $2 AND 'paper' = ANY(games)
ORDER BY release_date DESC
LIMIT $3 OFFSET $4
`

type SearchCardsByNameListParams struct {
	Column1 sql.NullString
	Lang    string
	Limit   int32
	Offset  int32
}

type SearchCardsByNameListRow struct {
	PrintedName sql.NullString
	SetName     string
	SetCode     string
	Rarity      string
}

func (q *Queries) SearchCardsByNameList(ctx context.Context, arg SearchCardsByNameListParams) ([]SearchCardsByNameListRow, error) {
	rows, err := q.db.QueryContext(ctx, searchCardsByNameList,
		arg.Column1,
		arg.Lang,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchCardsByNameListRow
	for rows.Next() {
		var i SearchCardsByNameListRow
		if err := rows.Scan(
			&i.PrintedName,
			&i.SetName,
			&i.SetCode,
			&i.Rarity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCardsByNameListEng = `-- name: SearchCardsByNameListEng :many
SELECT name, set_name, set_code, rarity FROM cards
WHERE name ILIKE '%' || $1 || '%' AND lang = 'en' AND 'paper' = ANY(games)
ORDER BY release_date DESC
LIMIT $2 OFFSET $3
`

type SearchCardsByNameListEngParams struct {
	Column1 sql.NullString
	Limit   int32
	Offset  int32
}

type SearchCardsByNameListEngRow struct {
	Name    string
	SetName string
	SetCode string
	Rarity  string
}

func (q *Queries) SearchCardsByNameListEng(ctx context.Context, arg SearchCardsByNameListEngParams) ([]SearchCardsByNameListEngRow, error) {
	rows, err := q.db.QueryContext(ctx, searchCardsByNameListEng, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchCardsByNameListEngRow
	for rows.Next() {
		var i SearchCardsByNameListEngRow
		if err := rows.Scan(
			&i.Name,
			&i.SetName,
			&i.SetCode,
			&i.Rarity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
