// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: collections.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addCardToCollections = `-- name: AddCardToCollections :exec
INSERT INTO collections (id, user_id, folder_id, scryfall_id, purchase_date, purchase_price, finish, condition, created_at)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    NOW()
)
`

type AddCardToCollectionsParams struct {
	UserID        uuid.UUID
	FolderID      uuid.NullUUID
	ScryfallID    uuid.UUID
	PurchaseDate  time.Time
	PurchasePrice float64
	Finish        string
	Condition     string
}

func (q *Queries) AddCardToCollections(ctx context.Context, arg AddCardToCollectionsParams) error {
	_, err := q.db.ExecContext(ctx, addCardToCollections,
		arg.UserID,
		arg.FolderID,
		arg.ScryfallID,
		arg.PurchaseDate,
		arg.PurchasePrice,
		arg.Finish,
		arg.Condition,
	)
	return err
}
