// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: collections.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addCardToCollections = `-- name: AddCardToCollections :exec
INSERT INTO collections (id, user_id, folder_id, scryfall_id, purchase_date, purchase_price, finish, condition, created_at)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    NOW()
)
`

type AddCardToCollectionsParams struct {
	UserID        uuid.UUID
	FolderID      uuid.NullUUID
	ScryfallID    uuid.UUID
	PurchaseDate  time.Time
	PurchasePrice float64
	Finish        string
	Condition     string
}

func (q *Queries) AddCardToCollections(ctx context.Context, arg AddCardToCollectionsParams) error {
	_, err := q.db.ExecContext(ctx, addCardToCollections,
		arg.UserID,
		arg.FolderID,
		arg.ScryfallID,
		arg.PurchaseDate,
		arg.PurchasePrice,
		arg.Finish,
		arg.Condition,
	)
	return err
}

const createFolder = `-- name: CreateFolder :one
INSERT INTO folders (id, user_id, folder_name, created_at, updated_at)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    NOW(),
    NOW()
)
RETURNING id, user_id, folder_name, created_at, updated_at
`

type CreateFolderParams struct {
	UserID     uuid.NullUUID
	FolderName string
}

func (q *Queries) CreateFolder(ctx context.Context, arg CreateFolderParams) (Folder, error) {
	row := q.db.QueryRowContext(ctx, createFolder, arg.UserID, arg.FolderName)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FolderName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFolderByUserAndName = `-- name: GetFolderByUserAndName :one
SELECT id, user_id, folder_name, created_at, updated_at FROM folders
WHERE user_id = $1 AND folder_name = $2
`

type GetFolderByUserAndNameParams struct {
	UserID     uuid.NullUUID
	FolderName string
}

func (q *Queries) GetFolderByUserAndName(ctx context.Context, arg GetFolderByUserAndNameParams) (Folder, error) {
	row := q.db.QueryRowContext(ctx, getFolderByUserAndName, arg.UserID, arg.FolderName)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FolderName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
