// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: migration.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const getSyncState = `-- name: GetSyncState :one
SELECT last_sync FROM sync_state WHERE key = $1
`

func (q *Queries) GetSyncState(ctx context.Context, key string) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, getSyncState, key)
	var last_sync time.Time
	err := row.Scan(&last_sync)
	return last_sync, err
}

const insertCard = `-- name: InsertCard :exec
INSERT INTO cards (
    id, arena_id, mtgo_id, cardmarket_id, oracle_id, release_date,
    lang, layout, edhrec_rank, game_changer, multifaced,
    cmc, color_identity, colors, defense, keywords, loyalty,
    mana_cost, name, oracle_text, power, toughness, type_line,
    artist, collector_number, finishes, flavor_name, flavor_text,
    games, image, image_png, image_large, image_small, image_crop,
    price_usd, price_eur, price_foil_usd, price_foil_eur, price_etched_usd,
    printed_name, printed_text, printed_type_line,
    rarity, set_name, set_code,
    created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10, $11,
    $12, $13, $14, $15, $16, $17,
    $18, $19, $20, $21, $22, $23,
    $24, $25, $26, $27, $28,
    $29, $30, $31, $32,
    $33, $34, $35, $36,
    $37, $38, $39,
    $40, $41, $42, $43, $44, $45,
    NOW(), NOW()
)
ON CONFLICT (id) DO UPDATE SET
    arena_id = EXCLUDED.arena_id,
    mtgo_id = EXCLUDED.mtgo_id,
    cardmarket_id = EXCLUDED.cardmarket_id,
    oracle_id = EXCLUDED.oracle_id,
    release_date = EXCLUDED.release_date,
    lang = EXCLUDED.lang,
    layout = EXCLUDED.layout,
    edhrec_rank = EXCLUDED.edhrec_rank,
    game_changer = EXCLUDED.game_changer,
    multifaced = EXCLUDED.multifaced,
    cmc = EXCLUDED.cmc,
    color_identity = EXCLUDED.color_identity,
    colors = EXCLUDED.colors,
    defense = EXCLUDED.defense,
    keywords = EXCLUDED.keywords,
    loyalty = EXCLUDED.loyalty,
    mana_cost = EXCLUDED.mana_cost,
    name = EXCLUDED.name,
    oracle_text = EXCLUDED.oracle_text,
    power = EXCLUDED.power,
    toughness = EXCLUDED.toughness,
    type_line = EXCLUDED.type_line,
    artist = EXCLUDED.artist,
    collector_number = EXCLUDED.collector_number,
    finishes = EXCLUDED.finishes,
    flavor_name = EXCLUDED.flavor_name,
    flavor_text = EXCLUDED.flavor_text,
    games = EXCLUDED.games,
    image = EXCLUDED.image,
    image_png = EXCLUDED.image_png,
    image_large = EXCLUDED.image_large,
    image_small = EXCLUDED.image_small,
    image_crop = EXCLUDED.image_crop,
    price_usd = EXCLUDED.price_usd,
    price_eur = EXCLUDED.price_eur,
    price_foil_usd = EXCLUDED.price_foil_usd,
    price_foil_eur = EXCLUDED.price_foil_eur,
    price_etched_usd = EXCLUDED.price_etched_usd,
    printed_name = EXCLUDED.printed_name,
    printed_text = EXCLUDED.printed_text,
    printed_type_line = EXCLUDED.printed_type_line,
    rarity = EXCLUDED.rarity,
    set_name = EXCLUDED.set_name,
    set_code = EXCLUDED.set_code,
    updated_at = NOW()
`

type InsertCardParams struct {
	ID              uuid.UUID
	ArenaID         sql.NullInt64
	MtgoID          sql.NullInt64
	CardmarketID    sql.NullInt64
	OracleID        uuid.NullUUID
	ReleaseDate     time.Time
	Lang            string
	Layout          string
	EdhrecRank      sql.NullInt32
	GameChanger     sql.NullBool
	Multifaced      bool
	Cmc             float64
	ColorIdentity   []string
	Colors          []string
	Defense         sql.NullString
	Keywords        []string
	Loyalty         sql.NullString
	ManaCost        sql.NullString
	Name            string
	OracleText      sql.NullString
	Power           sql.NullString
	Toughness       sql.NullString
	TypeLine        string
	Artist          sql.NullString
	CollectorNumber string
	Finishes        []string
	FlavorName      sql.NullString
	FlavorText      sql.NullString
	Games           []string
	Image           sql.NullString
	ImagePng        sql.NullString
	ImageLarge      sql.NullString
	ImageSmall      sql.NullString
	ImageCrop       sql.NullString
	PriceUsd        sql.NullFloat64
	PriceEur        sql.NullFloat64
	PriceFoilUsd    sql.NullFloat64
	PriceFoilEur    sql.NullFloat64
	PriceEtchedUsd  sql.NullFloat64
	PrintedName     sql.NullString
	PrintedText     sql.NullString
	PrintedTypeLine sql.NullString
	Rarity          string
	SetName         string
	SetCode         string
}

func (q *Queries) InsertCard(ctx context.Context, arg InsertCardParams) error {
	_, err := q.db.ExecContext(ctx, insertCard,
		arg.ID,
		arg.ArenaID,
		arg.MtgoID,
		arg.CardmarketID,
		arg.OracleID,
		arg.ReleaseDate,
		arg.Lang,
		arg.Layout,
		arg.EdhrecRank,
		arg.GameChanger,
		arg.Multifaced,
		arg.Cmc,
		pq.Array(arg.ColorIdentity),
		pq.Array(arg.Colors),
		arg.Defense,
		pq.Array(arg.Keywords),
		arg.Loyalty,
		arg.ManaCost,
		arg.Name,
		arg.OracleText,
		arg.Power,
		arg.Toughness,
		arg.TypeLine,
		arg.Artist,
		arg.CollectorNumber,
		pq.Array(arg.Finishes),
		arg.FlavorName,
		arg.FlavorText,
		pq.Array(arg.Games),
		arg.Image,
		arg.ImagePng,
		arg.ImageLarge,
		arg.ImageSmall,
		arg.ImageCrop,
		arg.PriceUsd,
		arg.PriceEur,
		arg.PriceFoilUsd,
		arg.PriceFoilEur,
		arg.PriceEtchedUsd,
		arg.PrintedName,
		arg.PrintedText,
		arg.PrintedTypeLine,
		arg.Rarity,
		arg.SetName,
		arg.SetCode,
	)
	return err
}

const insertCardFace = `-- name: InsertCardFace :exec
INSERT INTO card_faces (
    card_id, face_index,
    artist, cmc, colors, defense,
    flavor_text, image, image_png, image_large, image_small, image_crop,
    layout, loyalty, mana_cost, name, oracle_text,
    power, printed_name, printed_text, printed_type_line,
    toughness, type_line, created_at, updated_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6, $7, $8,
    $9, $10, $11, $12,
    $13, $14, $15, $16, $17,
    $18, $19, $20, $21,
    $22, $23, Now(), Now()
)
ON CONFLICT (card_id, face_index) DO UPDATE SET
    artist = EXCLUDED.artist,
    cmc = EXCLUDED.cmc,
    colors = EXCLUDED.colors,
    defense = EXCLUDED.defense,
    flavor_text = EXCLUDED.flavor_text,
    image = EXCLUDED.image,
    image_png = EXCLUDED.image_png,
    image_large = EXCLUDED.image_large,
    image_small = EXCLUDED.image_small,
    image_crop = EXCLUDED.image_crop,
    layout = EXCLUDED.layout,
    loyalty = EXCLUDED.loyalty,
    mana_cost = EXCLUDED.mana_cost,
    name = EXCLUDED.name,
    oracle_text = EXCLUDED.oracle_text,
    power = EXCLUDED.power,
    printed_name = EXCLUDED.printed_name,
    printed_text = EXCLUDED.printed_text,
    printed_type_line = EXCLUDED.printed_type_line,
    toughness = EXCLUDED.toughness,
    type_line = EXCLUDED.type_line,
    updated_at = Now()
`

type InsertCardFaceParams struct {
	CardID          uuid.UUID
	FaceIndex       int32
	Artist          sql.NullString
	Cmc             sql.NullFloat64
	Colors          []string
	Defense         sql.NullString
	FlavorText      sql.NullString
	Image           sql.NullString
	ImagePng        sql.NullString
	ImageLarge      sql.NullString
	ImageSmall      sql.NullString
	ImageCrop       sql.NullString
	Layout          sql.NullString
	Loyalty         sql.NullString
	ManaCost        string
	Name            string
	OracleText      sql.NullString
	Power           sql.NullString
	PrintedName     sql.NullString
	PrintedText     sql.NullString
	PrintedTypeLine sql.NullString
	Toughness       sql.NullString
	TypeLine        sql.NullString
}

func (q *Queries) InsertCardFace(ctx context.Context, arg InsertCardFaceParams) error {
	_, err := q.db.ExecContext(ctx, insertCardFace,
		arg.CardID,
		arg.FaceIndex,
		arg.Artist,
		arg.Cmc,
		pq.Array(arg.Colors),
		arg.Defense,
		arg.FlavorText,
		arg.Image,
		arg.ImagePng,
		arg.ImageLarge,
		arg.ImageSmall,
		arg.ImageCrop,
		arg.Layout,
		arg.Loyalty,
		arg.ManaCost,
		arg.Name,
		arg.OracleText,
		arg.Power,
		arg.PrintedName,
		arg.PrintedText,
		arg.PrintedTypeLine,
		arg.Toughness,
		arg.TypeLine,
	)
	return err
}

const insertLegality = `-- name: InsertLegality :exec
INSERT INTO legalities (
    card_id, standard, pauper, vintage, pioneer, modern, legacy, commander, future,
	historic, timeless, gladiator, penny, oathbreaker,
	standardbrawl, brawl, alchemy, paupercommander, duel,
	oldschool, premodern, predh, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12,
    $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, Now(), Now()
)
ON CONFLICT (card_id) DO UPDATE SET
    standard = EXCLUDED.standard,
    pauper = EXCLUDED.pauper,
    vintage = EXCLUDED.vintage,
    pioneer = EXCLUDED.pioneer,
    modern = EXCLUDED.modern,
    legacy = EXCLUDED.legacy,
    commander = EXCLUDED.commander,
	future = EXCLUDED.future,
	historic = EXCLUDED.historic,
	timeless = EXCLUDED.timeless,
	gladiator = EXCLUDED.gladiator,
	penny = EXCLUDED.penny,
	oathbreaker = EXCLUDED.oathbreaker,
	standardbrawl = EXCLUDED.standardbrawl,
	brawl = EXCLUDED.brawl,
	alchemy = EXCLUDED.alchemy,
	paupercommander = EXCLUDED.paupercommander,
	duel = EXCLUDED.duel,
	oldschool = EXCLUDED.oldschool,
	premodern = EXCLUDED.premodern,
	predh = EXCLUDED.predh,
    updated_at = Now()
`

type InsertLegalityParams struct {
	CardID          uuid.UUID
	Standard        sql.NullString
	Pauper          sql.NullString
	Vintage         sql.NullString
	Pioneer         sql.NullString
	Modern          sql.NullString
	Legacy          sql.NullString
	Commander       sql.NullString
	Future          sql.NullString
	Historic        sql.NullString
	Timeless        sql.NullString
	Gladiator       sql.NullString
	Penny           sql.NullString
	Oathbreaker     sql.NullString
	Standardbrawl   sql.NullString
	Brawl           sql.NullString
	Alchemy         sql.NullString
	Paupercommander sql.NullString
	Duel            sql.NullString
	Oldschool       sql.NullString
	Premodern       sql.NullString
	Predh           sql.NullString
}

func (q *Queries) InsertLegality(ctx context.Context, arg InsertLegalityParams) error {
	_, err := q.db.ExecContext(ctx, insertLegality,
		arg.CardID,
		arg.Standard,
		arg.Pauper,
		arg.Vintage,
		arg.Pioneer,
		arg.Modern,
		arg.Legacy,
		arg.Commander,
		arg.Future,
		arg.Historic,
		arg.Timeless,
		arg.Gladiator,
		arg.Penny,
		arg.Oathbreaker,
		arg.Standardbrawl,
		arg.Brawl,
		arg.Alchemy,
		arg.Paupercommander,
		arg.Duel,
		arg.Oldschool,
		arg.Premodern,
		arg.Predh,
	)
	return err
}

const insertRulings = `-- name: InsertRulings :exec
INSERT INTO rulings (
    oracle_id, source, published_at, comment, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, Now(), Now()
)
ON CONFLICT (oracle_id, published_at, comment) DO NOTHING
`

type InsertRulingsParams struct {
	OracleID    uuid.UUID
	Source      sql.NullString
	PublishedAt time.Time
	Comment     string
}

func (q *Queries) InsertRulings(ctx context.Context, arg InsertRulingsParams) error {
	_, err := q.db.ExecContext(ctx, insertRulings,
		arg.OracleID,
		arg.Source,
		arg.PublishedAt,
		arg.Comment,
	)
	return err
}

const insertSyncState = `-- name: InsertSyncState :exec
INSERT INTO sync_state (
key, last_sync
) VALUES (
    $1, Now()
)
ON CONFLICT (key) DO UPDATE SET
    last_sync = Now()
`

func (q *Queries) InsertSyncState(ctx context.Context, key string) error {
	_, err := q.db.ExecContext(ctx, insertSyncState, key)
	return err
}
