// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Card struct {
	ID              uuid.UUID
	ArenaID         sql.NullInt64
	MtgoID          sql.NullInt64
	CardmarketID    sql.NullInt64
	OracleID        uuid.NullUUID
	ReleaseDate     time.Time
	Lang            string
	Layout          string
	RulingUri       string
	EdhrecRank      sql.NullInt32
	GameChanger     sql.NullBool
	Multifaced      bool
	Cmc             float64
	ColorIdentity   []string
	Colors          []string
	Defense         sql.NullString
	Keywords        []string
	Loyalty         sql.NullString
	ManaCost        sql.NullString
	Name            string
	OracleText      sql.NullString
	Power           sql.NullString
	Toughness       sql.NullString
	TypeLine        string
	Artist          sql.NullString
	CollectorNumber string
	Finishes        []string
	FlavorName      sql.NullString
	FlavorText      sql.NullString
	Games           []string
	Image           sql.NullString
	ImagePng        sql.NullString
	ImageLarge      sql.NullString
	ImageSmall      sql.NullString
	ImageCrop       sql.NullString
	PriceUsd        sql.NullFloat64
	PriceEur        sql.NullFloat64
	PriceFoilUsd    sql.NullFloat64
	PriceFoilEur    sql.NullFloat64
	PriceEtchedUsd  sql.NullFloat64
	PrintedName     sql.NullString
	PrintedText     sql.NullString
	PrintedTypeLine sql.NullString
	Rarity          string
	SetName         string
	SetCode         string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type CardFace struct {
	CardID          uuid.UUID
	FaceIndex       int32
	Artist          sql.NullString
	Cmc             sql.NullFloat64
	Colors          []string
	Defense         sql.NullString
	FlavorText      sql.NullString
	Image           sql.NullString
	ImagePng        sql.NullString
	ImageLarge      sql.NullString
	ImageSmall      sql.NullString
	ImageCrop       sql.NullString
	Layout          sql.NullString
	Loyalty         sql.NullString
	ManaCost        string
	Name            string
	OracleText      sql.NullString
	Power           sql.NullString
	PrintedName     sql.NullString
	PrintedText     sql.NullString
	PrintedTypeLine sql.NullString
	Toughness       sql.NullString
	TypeLine        sql.NullString
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Legality struct {
	ID              uuid.UUID
	Standard        sql.NullString
	Pauper          sql.NullString
	Vintage         sql.NullString
	Pioneer         sql.NullString
	Modern          sql.NullString
	Legacy          sql.NullString
	Commander       sql.NullString
	Future          sql.NullString
	Historic        sql.NullString
	Timeless        sql.NullString
	Gladiator       sql.NullString
	Penny           sql.NullString
	Oathbreaker     sql.NullString
	Standardbrawl   sql.NullString
	Brawl           sql.NullString
	Alchemy         sql.NullString
	Paupercommander sql.NullString
	Duel            sql.NullString
	Oldschool       sql.NullString
	Premodern       sql.NullString
	Predh           sql.NullString
	CreatedAt       time.Time
	UpdatedAt       time.Time
}
