// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	AddCardToCollections(ctx context.Context, arg AddCardToCollectionsParams) error
	CountCardsByNameList(ctx context.Context, arg CountCardsByNameListParams) (int64, error)
	CountCardsByNameListEng(ctx context.Context, dollar_1 sql.NullString) (int64, error)
	CountCardsByOracleIDList(ctx context.Context, arg CountCardsByOracleIDListParams) (int64, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DoesLangExist(ctx context.Context, lang string) (string, error)
	GetCardByID(ctx context.Context, id uuid.UUID) (Card, error)
	GetCardFaces(ctx context.Context, cardID uuid.UUID) ([]CardFace, error)
	GetCardLegalties(ctx context.Context, cardID uuid.UUID) (Legality, error)
	GetOneUniqueCard(ctx context.Context, arg GetOneUniqueCardParams) (uuid.UUID, error)
	GetOracleRulings(ctx context.Context, oracleID uuid.UUID) ([]Ruling, error)
	GetSyncState(ctx context.Context, key string) (time.Time, error)
	GetUserByUserName(ctx context.Context, userName string) (User, error)
	GetUserFromRefreshToken(ctx context.Context, token string) (User, error)
	InsertCard(ctx context.Context, arg InsertCardParams) error
	InsertCardFace(ctx context.Context, arg InsertCardFaceParams) error
	InsertLegality(ctx context.Context, arg InsertLegalityParams) error
	InsertRulings(ctx context.Context, arg InsertRulingsParams) error
	InsertSyncState(ctx context.Context, key string) error
	RevokeRefreshToken(ctx context.Context, token string) (RefreshToken, error)
	SearchCardByOracleID(ctx context.Context, arg SearchCardByOracleIDParams) (Card, error)
	SearchCardsByNameList(ctx context.Context, arg SearchCardsByNameListParams) ([]SearchCardsByNameListRow, error)
	SearchCardsByNameListEng(ctx context.Context, arg SearchCardsByNameListEngParams) ([]SearchCardsByNameListEngRow, error)
	SearchCardsByOracleIDList(ctx context.Context, arg SearchCardsByOracleIDListParams) ([]SearchCardsByOracleIDListRow, error)
}

var _ Querier = (*Queries)(nil)
